theme: jekyll-theme-minimal
title: "Topic Models in R"
description: "5 December 2018, 9 - 12:30 | Location: TBD, The University of Sydney"
logo: "https://digital-methods-sydney.github.io/ws-201806/img/digital-methods-logo.png"